name: Build Pop!_OS ISO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager

    - name: Install Required Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git live-build debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin mtools
        
    - name: Clone Pop!_OS Build Repository
      run: git clone https://github.com/pop-os/iso.git popos-iso

    - name: Configure and Build ISO
      working-directory: popos-iso
      run: |
        sudo make configure
        sudo make build

    - name: Archive ISO
      uses: actions/upload-artifact@v2
      with:
        name: popos-noble.iso
        path: popos-iso/build/live-image-amd64.hybrid.iso
